default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/tomnagengast/work/syncr/database.db
      extensions:
        - httpfs
        - parquet
      settings:
        s3_endpoint: ''
        s3_access_key_id: ''
        s3_secret_access_key: ''

replit:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      project: replit-analytics-dev
      dataset: "{{ env_var('TARGET_SCHEMA', 'dev_tom') }}"
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      # method: service-account
      # keyfile: /Users/tomnagengast/.config/gcloud/data-platform-staging@replit-analytics.iam.gserviceaccount.com.json
    staging:
      type: bigquery
      project: replit-analytics-dev
      dataset: "{{ env_var('TARGET_SCHEMA', 'PR_305_DEV') }}"
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      # method: service-account
      # keyfile: /Users/tomnagengast/.config/gcloud/data-platform-staging@replit-analytics.iam.gserviceaccount.com.json
    production:
      type: bigquery
      project: replit-analytics
      execution_project: replit-analytics
      dataset: core_data_deps
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth

cortex:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: replit-analytics-dev
      dataset: "{{ env_var('TARGET_SCHEMA', 'dev_tom') }}"
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
    stag:
      type: bigquery
      project: replit-analytics-dev
      dataset: "{{ env_var('TARGET_SCHEMA', 'pr_test') }}"
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      impersonate_service_account: cortex-github@replit-analytics-dev.iam.gserviceaccount.com
    prod:
      type: bigquery
      project: replit-analytics
      dataset: warehouse
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      # method: service-account
      # keyfile: /Users/tomnagengast/.config/gcloud/data-platform-staging@replit-analytics.iam.gserviceaccount.com.json
