replit:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: replit-analytics
      dataset: dev_tom
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      # method: service-account
      # keyfile: /Users/tomnagengast/.config/gcloud/replit-analytics-service-account-data-platform-staging.json
    staging:
      type: bigquery
      project: replit-analytics-dev
      dataset: PR_35
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      # method: oauth
      method: service-account
      keyfile: /Users/tomnagengast/.config/gcloud/replit-analytics-service-account-data-platform-staging.json
    production:
      type: bigquery
      project: replit-analytics
      execution_project: replit-analytics
      dataset: core_data_deps
      location: US
      threads: 25
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth

