
# bindkey -s ^f "t\n" # tmux-sessionizer

eval "$(/opt/homebrew/bin/brew shellenv)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/tomnagengast/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/tomnagengast/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/tomnagengast/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/tomnagengast/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
