export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR="cursor"

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/zsh
DISABLE_UPDATE_PROMPT="true"
HIST_STAMPS="yyyy-mm-dd HH:MM:SS"
fpath+=("/opt/homebrew/share/zsh")
fpath+=("/opt/homebrew/share/zsh/site-functions")
autoload -Uz compinit && compinit -i

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse bgnotify web-search)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh
zstyle ':omz:update' mode auto # auto update oh-my-zsh

# Load Pure iTerm theme https://github.com/sindresorhus/pure
autoload -U promptinit
promptinit
zstyle :prompt:pure:git:branch color '#56526e'
zstyle :prompt:pure:git:dirty color '#56526e'
zstyle :prompt:pure:path color green
zstyle ':prompt:pure:prompt:*' color cyan
zstyle :prompt:pure:prompt:continuation color cyan
zstyle :prompt:pure:virtualenv color cyan
prompt pure

# dbt
export DBT_STATE=target/production
export DBT_DEFER=true
export DBT_CLOUD_ACCOUNT_ID=211006
export DBT_CLOUD_PROJECT_ID=304574

# Herd injected NVM configuration
export NVM_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"

# Herd injected PHP binary.
export PATH="/Users/tomnagengast/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/82/"

# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/83/"

. "$HOME/.cargo/env"
# dbt
export DBT_STATE=target/production
export DBT_DEFER=true
export DBT_CLOUD_ACCOUNT_ID=211006
export DBT_CLOUD_PROJECT_ID=304574

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/tomnagengast/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/tomnagengast/Downloads/google-cloud-sdk/path.zsh.inc'; fi



# Herd injected PHP binary.
export PATH="/Users/tomnagengast/Library/Application Support/Herd/bin/":$PATH
. "$HOME/.cargo/env"
