export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR='nvim'

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/zsh
DISABLE_UPDATE_PROMPT="true"
HIST_STAMPS="yyyy-mm-dd HH:MM:SS"
# BREW_PREFIX=$(brew --prefix)
fpath+=("/opt/homebrew/share/zsh")
fpath+=("/opt/homebrew/share/zsh/site-functions")
autoload -Uz compinit && compinit -i

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse bgnotify web-search)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Load Pure iTerm theme https://github.com/sindresorhus/pure
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:branch color '#56526e'
zstyle :prompt:pure:git:dirty color '#56526e'
zstyle :prompt:pure:path color green
zstyle ':prompt:pure:prompt:*' color cyan
zstyle :prompt:pure:prompt:continuation color cyan
zstyle :prompt:pure:virtualenv color cyan
prompt pure

# Bun
[ -s "/Users/tomnagengast/.bun/_bun" ] && source "/Users/tomnagengast/.bun/_bun"
export BUN_INSTALL="/Users/tomnagengast/.bun"

# For Java
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export JAVA_HOME="/opt/homebrew/opt/openjdk"

# dbt
export DBT_STATE=target/production
export DBT_DEFER=true
export DBT_CLOUD_ACCOUNT_ID=211006
export DBT_CLOUD_PROJECT_ID=304574

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# Silence punycode deprecation warning
export NODE_OPTIONS="--no-deprecation"
# Set max old space size for CDKTF ts
export NODE_OPTIONS="${NODE_OPTIONS} --max-old-space-size=4096"

# pnpm
export PNPM_HOME="/Users/tomnagengast/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# . "$HOME/.cargo/env"

# nix & direnv
# if [[ "$PWD" == "$HOME/work"* ]]; then
#     mkdir -p "${HOME}/.config/direnv"
#     echo 'source $HOME/.nix-profile/share/nix-direnv/direnvrc' >> "${HOME}/.config/direnv/direnvrc"
#     eval "$(direnv hook zsh)"
# fi

# run source ./venv/bin/activate if directory contains venv
if [ -d "./venv" ]; then
    source ./venv/bin/activate
fi

# Herd
export PATH="/Users/tomnagengast/Library/Application Support/Herd/bin/":$PATH
export PHP_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/":$PHP_INI_SCAN_DIR
export HERD_PHP_82_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/82/"
export HERD_PHP_83_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/83/"
export HERD_PHP_84_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/84/"
