export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR='nvim'

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/zsh
DISABLE_UPDATE_PROMPT="true"
HIST_STAMPS="yyyy-mm-dd HH:MM:SS"
fpath+=("$(brew --prefix)/share/zsh")
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -Uz compinit && compinit -i

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse bgnotify web-search)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Load Pure iTerm theme https://github.com/sindresorhus/pure
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:branch color '#56526e'
zstyle :prompt:pure:git:dirty color '#56526e'
zstyle :prompt:pure:path color green
zstyle ':prompt:pure:prompt:*' color cyan
zstyle :prompt:pure:prompt:continuation color cyan
zstyle :prompt:pure:virtualenv color cyan
prompt pure

# Bun
[ -s "/Users/tomnagengast/.bun/_bun" ] && source "/Users/tomnagengast/.bun/_bun"
export BUN_INSTALL="/Users/tomnagengast/.bun"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PYENV_SHELL="zsh"
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init -)"
#   eval "$(pyenv virtualenv-init -)"
# fi
# For pyenv: https://stackoverflow.com/questions/50036091/pyenv-zlib-error-on-macos
export LDFLAGS="-L $(xcrun --show-sdk-path)/usr/lib"
export CFLAGS="-L $(xcrun --show-sdk-path)/usr/include -L brew --prefix bzip2/include"

# Herd
export PHP_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/":$PHP_INI_SCAN_DIR
export HERD_PHP_82_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/82/"
export HERD_PHP_83_INI_SCAN_DIR="/Users/tomnagengast/Library/Application Support/Herd/config/php/83/"
